### PR TITLE
Python 3

### PR DESCRIPTION
**Pull request by ross-spencer**
Connected to #15

### CODE REVIEW

**Comment by ross-spencer** [comment]
@richardlehane this is ready to be merged - here we convert the code to run on Python 3. It looks like this may only need you to remove Python 2 from: https://github.com/richardlehane/builder/blob/master/.github/workflows/builder.yaml (or at least the call to `python2`. Just let me know if that's okay before I merge and tag.)

There's a Python 2 tag here from the last working commit also just in case: https://github.com/exponential-decay/skeleton-test-suite-generator/releases/tag/v1.0

**Comment by anjackson** [comment]
I just used this and it seems to work. The tests aren't quite passing, but I think my PRONOM download is slightly ahead of the last sig file release (V111).

**Comment by richardlehane** [comment]
Sorry I missed this mention, I'll go ahead and update builder, don't wait for me!

**Comment by anjackson** [comment]
I might be missing something, but I seem to have some errors. Running the suite against a new version of Nanite, based on DROID 6.6, and I'm getting:

```
FAIL: File could not be identified! fmt-1757-signature-id-2095.iso : got fmt/1740
FAIL: File could not be identified! fmt-1062-signature-id-1435.3fr : got fmt/353
FAIL: File could not be identified! fmt-1757-signature-id-2094.iso : got fmt/1740
FAIL: File could not be identified! fmt-1739-signature-id-2077.toast : got fmt/468
FAIL: File could not be identified! fmt-1157-signature-id-1539.nfo : got null
```

Which seems to correspond to a subset of these `WARNING`s from when  I was running the skeleton generator:

```
WARNING: (fmt/1757):  Attempting to write BOF with BOF written.
WARNING: (fmt/1757):  Attempting to write BOF with BOF written.
WARNING: (fmt/1757):  Attempting to write BOF with BOF written.
WARNING: (fmt/1757):  Attempting to write BOF with BOF written.
WARNING: (fmt/363):   Attempting to write BOF with BOF written.
WARNING: (fmt/363):   Attempting to write BOF with BOF written.
WARNING: (fmt/558):   Attempting to write BOF with BOF written.
WARNING: (fmt/1345):  Attempting to write VAR with VAR written.
WARNING: (fmt/1157):  Attempting to write BOF with BOF written.
WARNING: (fmt/950):   Attempting to write BOF with BOF written.
WARNING: (fmt/950):   Attempting to write BOF with BOF written.
WARNING: (fmt/950):   Attempting to write BOF with BOF written.
WARNING: (fmt/950):   Attempting to write BOF with BOF written.
WARNING: (fmt/358):   Attempting to write BOF with BOF written.
WARNING: (fmt/358):   Attempting to write BOF with BOF written.
WARNING: (fmt/358):   Attempting to write BOF with BOF written.
WARNING: (fmt/894):   Attempting to write BOF with BOF written.
WARNING: (fmt/39):    Attempting to write VAR with VAR written.
WARNING: (fmt/125):   Attempting to write VAR with VAR written.
WARNING: (fmt/1062):  Attempting to write BOF with BOF written.
WARNING: (fmt/1739):  Attempting to write BOF with BOF written.
WARNING: (fmt/40):    Attempting to write VAR with VAR written.
WARNING: (fmt/1162):  Attempting to write BOF with BOF written.
WARNING: (fmt/965):   Attempting to write BOF with BOF written.
WARNING: (fmt/1163):  Attempting to write BOF with BOF written.
WARNING: (x-fmt/88):  Attempting to write VAR with VAR written.
WARNING: (x-fmt/388): Attempting to write BOF with BOF written.
WARNING: (x-fmt/388): Attempting to write BOF with BOF written.
WARNING: (x-fmt/399): Attempting to write BOF with BOF written.
WARNING: (x-fmt/399): Attempting to write BOF with BOF written.
WARNING: (x-fmt/430): Attempting to write VAR with VAR written.
WARNING: (x-fmt/387): Attempting to write BOF with BOF written.
WARNING: (x-fmt/387): Attempting to write BOF with BOF written.
```

But it could well be an issue with my analyser and how it handles multiple matches (I've not had chance to check that yet).

**Comment by richardlehane** [comment]
Hi @anjackson I fail on these tests too: I believe all these failures caused by this issue https://github.com/exponential-decay/skeleton-test-suite-generator/issues/11

**Comment by ross-spencer** [comment]
Thanks @anjackson and @richardlehane. Looks like this is good for me to merge. As for #11. I'll have to take a look finally. Probably in the next two weeks so I can take it to the PRONOM open chat next Thursday if need be.

**Comment by ross-spencer** [comment]
I appreciate you both taking a look at this PR btw! thanks! 🙏🙇

**Comment by ross-spencer** [comment]
Closes https://github.com/exponential-decay/skeleton-test-suite-generator/issues/15

**Pull request merged**
